[package]
name = "dogoap"
version = "0.6.0"
edition = "2021"
description = "dogoap"
license = "MIT"
homepage = "https://github.com/victorb/dogoap"

[dependencies]
bevy_reflect = { workspace = true }
pathfinding = { workspace = true }

[features]
# Define a feature for nightly usage
bench = []
